### ISSUE TITLE
v19: Unable to create GoogleAdsServiceClient

### ISSUE THREAD

**Issue by yanivkrol** [googleads/google-ads-java#833]
Hi,

We are trying to upgrade from v18 to v19 and faced the following issue when calling:
`client.getLatestVersion().createGoogleAdsServiceClient()` where client is `GoogleAdsClient`

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.ads.googleads.v19.services.stub.GoogleAdsServiceStubSettings$Builder
	at com.google.ads.googleads.v19.services.stub.GoogleAdsServiceStubSettings.newBuilder(GoogleAdsServiceStubSettings.java:261)
	at com.google.ads.googleads.v19.services.GoogleAdsServiceSettings$Builder.createDefault(GoogleAdsServiceSettings.java:185)
	at com.google.ads.googleads.v19.services.GoogleAdsServiceSettings$Builder.access$000(GoogleAdsServiceSettings.java:166)
	at com.google.ads.googleads.v19.services.GoogleAdsServiceSettings.newBuilder(GoogleAdsServiceSettings.java:148)
	at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V19Client.createGoogleAdsServiceClient(GeneratedCatalog.java:4750)
```

Everything worked well in 34.0.0 v18

**Client library version and API version:**
Client library version: 36.1.0
Google Ads API version: v19
JDK version: 11

maven dependency tree:

```
[INFO] com.ni:mc-extractor-google:jar:1.0-SNAPSHOT
[INFO] +- com.ni:mc-extractor-common:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.2.3.RELEASE:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-actuator:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.2:compile
[INFO] |  |  \- io.micrometer:micrometer-core:jar:1.3.2:compile
[INFO] |  |     +- org.hdrhistogram:HdrHistogram:jar:2.1.11:compile
[INFO] |  |     \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-batch:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  \- com.zaxxer:HikariCP:jar:3.4.2:compile
[INFO] |  |  \- org.springframework.batch:spring-batch-core:jar:4.2.1.RELEASE:compile
[INFO] |  |     +- javax.batch:javax.batch-api:jar:1.0:compile
[INFO] |  |     +- org.codehaus.jettison:jettison:jar:1.2:compile
[INFO] |  |     +- org.springframework.batch:spring-batch-infrastructure:jar:4.2.1.RELEASE:compile
[INFO] |  |     |  \- org.springframework.retry:spring-retry:jar:1.2.5.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-tx:jar:5.2.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.30:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.30:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-json:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.2:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.10.2:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  |  \- org.hibernate.validator:hibernate-validator:jar:6.0.18.Final:compile
[INFO] |  |  |     +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  |  |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.springframework:spring-web:jar:5.2.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:5.2.3.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-expression:jar:5.2.3.RELEASE:compile
[INFO] |  +- org.springframework.security.oauth:spring-security-oauth2:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:5.2.3.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.2.3.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-core:jar:5.2.1.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-config:jar:5.2.1.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-web:jar:5.2.1.RELEASE:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.13:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  +- org.springframework.shell:spring-shell-starter:jar:2.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework.shell:spring-shell-core:jar:2.0.1.RELEASE:compile
[INFO] |  |  |  +- org.jline:jline:jar:3.4.0:compile
[INFO] |  |  |  \- org.jline:jline-terminal-jna:jar:3.4.0:runtime
[INFO] |  |  |     +- net.java.dev.jna:jna:jar:4.5.2:runtime
[INFO] |  |  |     \- org.jline:jline-terminal:jar:3.4.0:runtime
[INFO] |  |  +- org.springframework.shell:spring-shell-standard:jar:2.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework.shell:spring-shell-standard-commands:jar:2.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework.shell:spring-shell-shell1-adapter:jar:2.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework.shell:spring-shell-jcommander-adapter:jar:2.0.1.RELEASE:compile
[INFO] |  |  \- org.springframework.shell:spring-shell-table:jar:2.0.1.RELEASE:compile
[INFO] |  +- com.naturalint:ni-secrets:jar:2.0.0:compile
[INFO] |  +- mysql:mysql-connector-java:jar:8.0.19:runtime
[INFO] |  +- net.javacrumbs.shedlock:shedlock-spring:jar:2.4.0:compile
[INFO] |  |  \- net.javacrumbs.shedlock:shedlock-core:jar:2.4.0:compile
[INFO] |  +- net.javacrumbs.shedlock:shedlock-provider-jdbc-template:jar:2.4.0:compile
[INFO] |  |  +- org.springframework:spring-jdbc:jar:5.2.3.RELEASE:compile
[INFO] |  |  \- net.javacrumbs.shedlock:shedlock-provider-jdbc-internal:jar:2.4.0:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.12.671:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.10.2:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.10.5:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-glue:jar:1.12.671:compile
[INFO] |  |  \- com.amazonaws:jmespath-java:jar:1.12.671:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-s3:jar:1.12.671:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-kms:jar:1.12.671:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-sns:jar:1.12.671:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.12.671:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-ssm:jar:1.12.671:compile
[INFO] |  +- org.apache.avro:avro:jar:1.9.1:compile
[INFO] |  |  \- org.apache.commons:commons-compress:jar:1.19:compile
[INFO] |  +- software.amazon.awssdk:metrics-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:annotations:jar:2.24.12:compile
[INFO] |  |  \- software.amazon.awssdk:utils:jar:2.24.12:compile
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  +- org.apache.parquet:parquet-avro:jar:1.13.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-column:jar:1.13.1:compile
[INFO] |  |  |  \- org.apache.parquet:parquet-encoding:jar:1.13.1:compile
[INFO] |  |  \- org.apache.parquet:parquet-common:jar:1.13.1:compile
[INFO] |  +- software.amazon.awssdk:s3:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:aws-xml-protocol:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:protocol-core:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:arns:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:profiles:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:crt-core:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:http-auth:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:identity-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:http-auth-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:http-auth-aws:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:checksums:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:checksums-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:sdk-core:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:auth:jar:2.24.12:compile
[INFO] |  |  |  \- software.amazon.eventstream:eventstream:jar:1.0.1:compile
[INFO] |  |  +- software.amazon.awssdk:http-client-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:regions:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:aws-core:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:json-utils:jar:2.24.12:compile
[INFO] |  |  |  \- software.amazon.awssdk:third-party-jackson-core:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:endpoints-spi:jar:2.24.12:compile
[INFO] |  |  +- software.amazon.awssdk:apache-client:jar:2.24.12:runtime
[INFO] |  |  \- software.amazon.awssdk:netty-nio-client:jar:2.24.12:runtime
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-codec-http2:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-codec:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-common:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-buffer:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-handler:jar:4.1.45.Final:runtime
[INFO] |  |     +- io.netty:netty-transport-classes-epoll:jar:4.1.107.Final:runtime
[INFO] |  |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.45.Final:runtime
[INFO] |  |     \- io.netty:netty-resolver:jar:4.1.45.Final:runtime
[INFO] |  +- software.amazon.awssdk:glue:jar:2.24.12:compile
[INFO] |  |  \- software.amazon.awssdk:aws-json-protocol:jar:2.24.12:compile
[INFO] |  +- software.amazon.awssdk:dynamodb:jar:2.24.12:compile
[INFO] |  +- software.amazon.awssdk:kms:jar:2.24.12:compile
[INFO] |  +- software.amazon.awssdk:url-connection-client:jar:2.24.12:compile
[INFO] |  +- software.amazon.awssdk:sts:jar:2.24.12:compile
[INFO] |  |  \- software.amazon.awssdk:aws-query-protocol:jar:2.24.12:compile
[INFO] |  +- org.apache.iceberg:iceberg-parquet:jar:1.4.3:compile
[INFO] |  |  \- org.apache.iceberg:iceberg-api:jar:1.4.3:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- org.projectlombok:lombok:jar:1.18.10:compile
[INFO] |  +- org.json:json:jar:20190722:compile
[INFO] |  +- com.opencsv:opencsv:jar:5.1:compile
[INFO] |  |  +- org.apache.commons:commons-text:jar:1.8:compile
[INFO] |  |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.10:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  +- io.micrometer:micrometer-registry-statsd:jar:1.3.2:compile
[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.12.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.12.1:compile
[INFO] |  +- net.logstash.logback:logstash-logback-encoder:jar:6.1:compile
[INFO] |  +- com.datadoghq:dd-java-agent:jar:0.30.0:compile
[INFO] |  +- org.apache.hadoop:hadoop-common:jar:3.1.0:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-annotations:jar:3.1.0:compile
[INFO] |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.1.1:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.6:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.25.v20191220:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.25.v20191220:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.25.v20191220:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util:jar:9.4.25.v20191220:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.25.v20191220:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.4.25.v20191220:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.25.v20191220:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.4.25.v20191220:compile
[INFO] |  |  +- javax.servlet.jsp:jsp-api:jar:2.1:runtime
[INFO] |  |  +- com.sun.jersey:jersey-core:jar:1.19:compile
[INFO] |  |  |  \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  +- com.sun.jersey:jersey-servlet:jar:1.19:compile
[INFO] |  |  +- com.sun.jersey:jersey-json:jar:1.19:compile
[INFO] |  |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO] |  |  |  |  \- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  |     \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.2:compile
[INFO] |  |  |  \- org.codehaus.jackson:jackson-xc:jar:1.9.2:compile
[INFO] |  |  +- com.sun.jersey:jersey-server:jar:1.19:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- org.apache.commons:commons-configuration2:jar:2.1.1:compile
[INFO] |  |  +- com.google.re2j:re2j:jar:1.1:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-auth:jar:3.1.0:compile
[INFO] |  |  |  +- com.nimbusds:nimbus-jose-jwt:jar:4.41.1:compile
[INFO] |  |  |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  |  \- org.apache.curator:curator-framework:jar:2.12.0:compile
[INFO] |  |  +- com.jcraft:jsch:jar:0.1.54:compile
[INFO] |  |  +- org.apache.curator:curator-client:jar:2.12.0:compile
[INFO] |  |  +- org.apache.curator:curator-recipes:jar:2.12.0:compile
[INFO] |  |  +- org.apache.htrace:htrace-core4:jar:4.1.0-incubating:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.9:compile
[INFO] |  |  |  +- jline:jline:jar:0.9.94:compile
[INFO] |  |  |  \- io.netty:netty:jar:3.10.5.Final:compile
[INFO] |  |  \- org.apache.kerby:kerb-simplekdc:jar:1.0.1:compile
[INFO] |  |     +- org.apache.kerby:kerb-client:jar:1.0.1:compile
[INFO] |  |     |  +- org.apache.kerby:kerby-config:jar:1.0.1:compile
[INFO] |  |     |  +- org.apache.kerby:kerb-core:jar:1.0.1:compile
[INFO] |  |     |  |  \- org.apache.kerby:kerby-pkix:jar:1.0.1:compile
[INFO] |  |     |  |     +- org.apache.kerby:kerby-asn1:jar:1.0.1:compile
[INFO] |  |     |  |     \- org.apache.kerby:kerby-util:jar:1.0.1:compile
[INFO] |  |     |  +- org.apache.kerby:kerb-common:jar:1.0.1:compile
[INFO] |  |     |  |  \- org.apache.kerby:kerb-crypto:jar:1.0.1:compile
[INFO] |  |     |  +- org.apache.kerby:kerb-util:jar:1.0.1:compile
[INFO] |  |     |  \- org.apache.kerby:token-provider:jar:1.0.1:compile
[INFO] |  |     \- org.apache.kerby:kerb-admin:jar:1.0.1:compile
[INFO] |  |        +- org.apache.kerby:kerb-server:jar:1.0.1:compile
[INFO] |  |        |  \- org.apache.kerby:kerb-identity:jar:1.0.1:compile
[INFO] |  |        \- org.apache.kerby:kerby-xdr:jar:1.0.1:compile
[INFO] |  +- org.apache.iceberg:iceberg-core:jar:1.4.3:compile
[INFO] |  |  +- io.airlift:aircompressor:jar:0.25:compile
[INFO] |  |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:runtime
[INFO] |  |  |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:runtime
[INFO] |  |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:runtime
[INFO] |  |  +- com.github.ben-manes.caffeine:caffeine:jar:2.8.0:runtime
[INFO] |  |  \- org.roaringbitmap:RoaringBitmap:jar:0.9.47:runtime
[INFO] |  |     \- org.roaringbitmap:shims:jar:0.9.47:runtime
[INFO] |  +- org.apache.iceberg:iceberg-bundled-guava:jar:1.4.3:compile
[INFO] |  +- org.apache.iceberg:iceberg-common:jar:1.4.3:compile
[INFO] |  +- org.apache.iceberg:iceberg-aws:jar:1.4.3:compile
[INFO] |  +- org.apache.hadoop:hadoop-core:jar:1.2.1:compile
[INFO] |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  +- commons-httpclient:commons-httpclient:jar:3.0.1:compile
[INFO] |  |  +- org.apache.commons:commons-math:jar:2.1:compile
[INFO] |  |  +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |  |  |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  |  \- commons-beanutils:commons-beanutils-core:jar:1.8.0:compile
[INFO] |  |  +- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO] |  |  |  \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  +- tomcat:jasper-runtime:jar:5.5.12:compile
[INFO] |  |  +- tomcat:jasper-compiler:jar:5.5.12:compile
[INFO] |  |  +- org.mortbay.jetty:jsp-api-2.1:jar:6.1.14:compile
[INFO] |  |  |  \- org.mortbay.jetty:servlet-api-2.5:jar:6.1.14:compile
[INFO] |  |  +- org.mortbay.jetty:jsp-2.1:jar:6.1.14:compile
[INFO] |  |  |  \- ant:ant:jar:1.6.5:compile
[INFO] |  |  +- commons-el:commons-el:jar:1.0:compile
[INFO] |  |  +- net.java.dev.jets3t:jets3t:jar:0.6.1:compile
[INFO] |  |  +- hsqldb:hsqldb:jar:1.8.0.10:compile
[INFO] |  |  +- oro:oro:jar:2.0.8:compile
[INFO] |  |  \- org.eclipse.jdt:core:jar:3.1.1:compile
[INFO] |  +- org.apache.parquet:parquet-hadoop:jar:1.13.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-format-structures:jar:1.13.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-jackson:jar:1.13.1:runtime
[INFO] |  |  +- org.xerial.snappy:snappy-java:jar:1.1.8.3:compile
[INFO] |  |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  |  +- com.github.luben:zstd-jni:jar:1.5.0-1:compile
[INFO] |  |  \- org.apache.yetus:audience-annotations:jar:0.13.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.2:compile
[INFO] |  \- org.flywaydb:flyway-core:jar:6.0.8:compile
[INFO] +- com.google.api-ads:google-ads:jar:36.1.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.25.5:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.70.0:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.24:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.70.0:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.70.0:runtime
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:1.33.1:compile
[INFO] |  +- com.google.api-ads:google-ads-codegen:jar:36.1.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-lib:jar:36.1.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v17:jar:36.1.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v18:jar:36.1.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v19:jar:36.1.0:compile
[INFO] |  |  \- com.squareup:javapoet:jar:1.11.1:runtime
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.25.5:runtime
[INFO] |  +- com.google.auto.service:auto-service:jar:1.0.1:runtime
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:runtime
[INFO] |  |  \- com.google.auto:auto-common:jar:1.2:runtime
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  \- com.google.auto.value:auto-value-annotations:jar:1.11.0:compile
[INFO] +- com.google.api:gax:jar:2.46.1:compile
[INFO] |  +- com.google.api:api-common:jar:2.29.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:2.37.1:compile
[INFO] |  +- org.threeten:threetenbp:jar:1.6.8:compile
[INFO] |  +- io.opencensus:opencensus-api:jar:0.31.1:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.27.2:compile
[INFO] |  \- io.opentelemetry:opentelemetry-api:jar:1.36.0:compile
[INFO] |     \- io.opentelemetry:opentelemetry-context:jar:1.36.0:compile
[INFO] +- com.google.api:gax-grpc:jar:2.46.1:compile
[INFO] |  +- io.grpc:grpc-api:jar:1.62.2:compile
[INFO] |  +- io.grpc:grpc-inprocess:jar:1.62.2:compile
[INFO] |  |  \- io.grpc:grpc-core:jar:1.62.2:compile
[INFO] |  |     \- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  +- io.grpc:grpc-alts:jar:1.62.2:compile
[INFO] |  |  +- io.grpc:grpc-grpclb:jar:1.62.2:compile
[INFO] |  |  \- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  +- io.grpc:grpc-auth:jar:1.62.2:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.62.2:compile
[INFO] |  |  +- io.grpc:grpc-util:jar:1.62.2:runtime
[INFO] |  |  \- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  \- io.grpc:grpc-googleapis:jar:1.62.2:runtime
[INFO] |     \- io.grpc:grpc-xds:jar:1.62.2:runtime
[INFO] |        +- io.opencensus:opencensus-proto:jar:0.2.0:runtime
[INFO] |        \- io.grpc:grpc-services:jar:1.62.2:runtime
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:1.23.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.43.3:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.31.1:compile
[INFO] |  +- com.google.http-client:google-http-client-gson:jar:1.43.3:compile
[INFO] |  \- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] +- javax.xml.soap:javax.xml.soap-api:jar:1.4.0:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.10.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.2:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.2:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.3:compile
[INFO] +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] +- org.joda:joda-convert:jar:2.2.0:compile
[INFO] \- org.springframework.boot:spring-boot-starter-test:jar:2.2.4.RELEASE:test
[INFO]    +- org.springframework.boot:spring-boot-starter:jar:2.2.4.RELEASE:compile
[INFO]    |  +- org.springframework.boot:spring-boot:jar:2.2.4.RELEASE:compile
[INFO]    |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.2.4.RELEASE:compile
[INFO]    |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.2.4.RELEASE:compile
[INFO]    |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO]    |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO]    |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO]    |  \- org.yaml:snakeyaml:jar:1.25:runtime
[INFO]    +- org.springframework.boot:spring-boot-test:jar:2.2.4.RELEASE:test
[INFO]    +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.2.4.RELEASE:test
[INFO]    +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO]    |  \- net.minidev:json-smart:jar:2.3:compile
[INFO]    |     \- net.minidev:accessors-smart:jar:1.2:compile
[INFO]    |        \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO]    +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO]    +- org.junit.jupiter:junit-jupiter:jar:5.5.2:test
[INFO]    |  +- org.junit.jupiter:junit-jupiter-api:jar:5.5.2:test
[INFO]    |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  |  \- org.junit.platform:junit-platform-commons:jar:1.5.2:test
[INFO]    |  +- org.junit.jupiter:junit-jupiter-params:jar:5.5.2:test
[INFO]    |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.5.2:test
[INFO]    +- org.junit.vintage:junit-vintage-engine:jar:5.5.2:test
[INFO]    |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO]    |  +- org.junit.platform:junit-platform-engine:jar:1.5.2:test
[INFO]    |  \- junit:junit:jar:4.12:compile
[INFO]    +- org.mockito:mockito-junit-jupiter:jar:3.1.0:test
[INFO]    +- org.assertj:assertj-core:jar:3.13.2:test
[INFO]    +- org.hamcrest:hamcrest:jar:2.1:test
[INFO]    +- org.mockito:mockito-core:jar:3.1.0:test
[INFO]    |  +- net.bytebuddy:byte-buddy:jar:1.10.6:test
[INFO]    |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.6:test
[INFO]    |  \- org.objenesis:objenesis:jar:2.6:test
[INFO]    +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO]    |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO]    +- org.springframework:spring-core:jar:5.2.3.RELEASE:compile
[INFO]    |  \- org.springframework:spring-jcl:jar:5.2.3.RELEASE:compile
[INFO]    +- org.springframework:spring-test:jar:5.2.3.RELEASE:test
[INFO]    \- org.xmlunit:xmlunit-core:jar:2.6.3:test
```

**Comment by jradcliff** [comment]
Could you share more of the stack trace or any warnings from logs around the time this exception is thrown?

Thanks,
Josh, Google Ads API Team

**Comment by yanivkrol** [comment]
Hi Josh,

There are no other warning at that time and the next call in the stack trace is our application code
(`client.getLatestVersion().createGoogleAdsServiceClient()`)

**Comment by jradcliff** [comment]
Does the log indicate which class it can't find? I see that the stubs project is in your classpath, so it looks like it can find `com.google.ads.googleads.v19.services.stub.GoogleAdsServiceStubSettings`, so I suspect that there's some dependency of that class that it can't find. From past experience, it's likely that there's a dependency conflict between your dependencies for Guava, protobuf, or grpc that's causing the issue.

For example, some likely candidates are:

* Guava:
  * You: `com.google.guava:guava:31.1-jre`
  * Ads: `com.google.guava:guava:33.4.0-jre`.
* GAX:
  * You: `com.google.api:gax:2.46.1`
  * Ads: `com.google.api:gax:2.63.1`
* Auth:
  * You: `com.google.auth:google-auth-library-oauth2-http:1.23.0`
  * Ads: `com.google.auth:google-auth-library-oauth2-http:1.33.1`

Are you able to upgrade any of those dependencies to match what `google-ads` expects?

Thanks,
Josh

**Comment by yanivkrol** [comment]
I will try and update, thanks
