### ISSUE TITLE
Resolve protobuf issues when upgrading from v16.0.1

### ISSUE THREAD

**Issue by vikrammmarkiv** [googleads/google-ads-java#584]
**What is your question?**
Hi, we are trying to upgrade from v16.0.1 however, when using any version from 16.0.1 onwards we are seeing protubuf errors during runtime.
Currently, we use version 2.6.1 of protobuf-java in our project and are not facing any issues with v16.0.1 of this library.
I can see that in version 16.0.2 a change was made to declare dependencies using gradle api config instead of implementation and this seems to be causing issues for us (#536).

Here is an example of the errors that we are seeing -

`! java.lang.NoSuchMethodError: com.google.protobuf.DescriptorProtos$FieldDescriptorProto.hasJsonName()Z
! at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:1400)
! at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:991)
! at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:899)
! at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:629)
! at com.google.protobuf.Descriptors$FileDescriptor.<init>(Descriptors.java:538)
! at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:311)
! at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:378)
! at com.google.protobuf.DescriptorProtos.<clinit>(DescriptorProtos.java:30111)
! at com.google.protobuf.DescriptorProtos$FileOptions.internalGetFieldAccessorTable(DescriptorProtos.java:14714)
! at com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:108)
! at com.google.protobuf.GeneratedMessage$ExtendableMessage.parseUnknownField(GeneratedMessage.java:978)
! at com.google.protobuf.DescriptorProtos$FileOptions.<init>(DescriptorProtos.java:14614)
! at com.google.protobuf.DescriptorProtos$FileOptions.<init>(DescriptorProtos.java:14570)
! at com.google.protobuf.DescriptorProtos$FileOptions$1.parsePartialFrom(DescriptorProtos.java:14725)
! at com.google.protobuf.DescriptorProtos$FileOptions$1.parsePartialFrom(DescriptorProtos.java:14720)
! at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
! at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1130)
! at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1023)
! at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1244)
! at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1239)
! at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
! at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
! at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
! at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
! at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
! at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:1883)
! at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:410)
! at com.google.api.HttpProto.<clinit>(HttpProto.java:67)
! at com.google.api.AnnotationsProto.<clinit>(AnnotationsProto.java:69)
! at com.google.ads.googleads.v9.enums.InteractionEventTypeProto.<clinit>(InteractionEventTypeProto.java:48)
! at com.google.ads.googleads.v9.common.MetricsProto.<clinit>(MetricsProto.java:266)
! at com.google.ads.googleads.v9.services.GoogleAdsServiceProto.<clinit>(GoogleAdsServiceProto.java:1139)
! at com.google.ads.googleads.v9.services.SearchGoogleAdsResponse.internalGetFieldAccessorTable(SearchGoogleAdsResponse.java:134)
! at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
! at com.google.ads.googleads.lib.logging.scrub.FieldDescriptorCache.lambda$lookupField$0(FieldDescriptorCache.java:55)
! at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
! at com.google.ads.googleads.lib.logging.scrub.FieldDescriptorCache.lookupField(FieldDescriptorCache.java:51)
! at com.google.ads.googleads.lib.logging.scrub.SearchResponseScrubber.setFieldIfPresent(SearchResponseScrubber.java:46)
! at com.google.ads.googleads.lib.logging.scrub.ReflectionScrubber.scrub(ReflectionScrubber.java:73)
! at com.google.ads.googleads.lib.logging.scrub.LogScrubber.scrub(LogScrubber.java:54)
! at com.google.ads.googleads.lib.logging.scrub.LogScrubber.edit(LogScrubber.java:46)
! at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:94)
! at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
! at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
! at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
! at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
! at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
! at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
! at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
! at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
! at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)`

`java.lang.NoClassDefFoundError: Could not initialize class com.google.protobuf.DescriptorProtos
	at com.google.api.FieldBehaviorProto.<clinit>(FieldBehaviorProto.java:83)
	at com.google.ads.googleads.v9.resources.CustomerClientProto.<clinit>(CustomerClientProto.java:64)
	at com.google.ads.googleads.v9.resources.CustomerClient.getDescriptor(CustomerClient.java:152)
	at com.google.ads.googleads.v9.resources.CustomerClient.hashCode(CustomerClient.java:829)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at io.project.ex.GoogleAdsUtil.createCustomerClientToHierarchy(GoogleAdsUtil.java:149)`

Can you suggest how we can upgrade to latest version of this lib without causing any protobuf issues?

**Comment by jradcliff** [comment]
Hi,

The library depends on `com.google.protobuf:protobuf-java:3.18.1`. Can you update to that version?

If upgrading that dependency is not an option due to other dependencies in your project, you could depend on our `com.google.api-ads:google-ads-shadowjar` artifact instead (see [this comment in issue 580](https://github.com/googleads/google-ads-java/issues/580#issuecomment-1056984989)).

Thanks,
Josh

**Comment by vikrammmarkiv** [comment]
@jradcliff Thanks! Using `google-ads-shadowjar` solved it for now.
