### ISSUE TITLE
Issue Encountered when Migrating from Google Ads v14 to v15 (java.lang.ClassNotFoundException: com.google.auth.oauth2.GdchCredentials)

### ISSUE THREAD

**Issue by ait-kaddi-ikram** [googleads/google-ads-java#749]
I am currently in the process of migrating from Google Ads API version 14 to version 15 in my Java-based project. During this migration, I have encountered a critical issue that I believe requires attention.

The issue arises when attempting to create a GoogleAdsServiceClient instance using the following code snippet:

try (GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()) {
 // Code implementation...
}

**The error message I am facing is as follows:**

**' nested exception is java.lang.NoClassDefFoundError: com/google/auth/oauth2/GdchCredentials]' with the root cause of 'java.lang.ClassNotFoundException: com.google.auth.oauth2.GdchCredentials.'**

**To resolve this issue, I attempted to create the GoogleAdsServiceClient using a CredentialsProvider, as demonstrated below:**

CredentialsProvider credentialsProvider = getCredentialsProvider(adsQuery.getClientId(), adsQuery.getClientSecret(), adsQuery.getClientToken());

GoogleAdsServiceSettings googleAdsServiceSettings = GoogleAdsServiceSettings.newBuilder().setCredentialsProvider(credentialsProvider).build();

try (GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()) {
 // Code implementation...
}

Despite these efforts, the problem persists.

Additional Information:
Java Version: 17
Google Ads API Version: 15 (28.0.0)

Dependency Tree:

[INFO] --- dependency:3.1.2:tree (default-cli) @ pads-ads ---
[INFO] com.pads:pads-ads:jar:1.0.8
[INFO] +- com.google.api-ads:google-ads:jar:28.0.0:compile
[INFO] |  +- com.google.api:gax:jar:2.32.0:compile
[INFO] |  |  +- com.google.api:api-common:jar:2.15.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.23.0:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.6.8:compile
[INFO] |  |  \- io.opencensus:opencensus-api:jar:0.31.1:compile
[INFO] |  |     \- io.grpc:grpc-context:jar:1.27.2:compile
[INFO] |  +- com.google.api:gax-grpc:jar:2.32.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.56.1:compile
[INFO] |  |  +- io.grpc:grpc-alts:jar:1.56.1:compile
[INFO] |  |  |  +- io.grpc:grpc-grpclb:jar:1.56.1:compile
[INFO] |  |  |  \- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.56.1:compile
[INFO] |  |  +- io.grpc:grpc-netty-shaded:jar:1.56.1:compile
[INFO] |  |  |  +- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  |  |  \- io.grpc:grpc-core:jar:1.56.1:compile
[INFO] |  |  |     +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.23:runtime
[INFO] |  |  \- io.grpc:grpc-googleapis:jar:1.56.1:runtime
[INFO] |  |     \- io.grpc:grpc-xds:jar:1.56.1:runtime
[INFO] |  |        +- io.opencensus:opencensus-proto:jar:0.2.0:runtime
[INFO] |  |        +- io.grpc:grpc-services:jar:1.56.1:runtime
[INFO] |  |        \- com.google.re2j:re2j:jar:1.7:runtime
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.23.2:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.56.1:compile
[INFO] |  |  \- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.56.1:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.56.1:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:1.19.0:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:1.19.0:compile
[INFO] |  +- com.google.api-ads:google-ads-codegen:jar:28.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-lib:jar:28.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v13:jar:28.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v14:jar:28.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v15:jar:28.0.0:compile
[INFO] |  |  \- com.squareup:javapoet:jar:1.11.1:runtime
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.23.2:runtime
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- com.google.guava:guava:jar:32.1.2-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  \- org.checkerframework:checker-qual:jar:3.33.0:compile
[INFO] |  +- com.google.auto.service:auto-service:jar:1.0.1:runtime
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:runtime
[INFO] |  |  \- com.google.auto:auto-common:jar:1.2:runtime
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  \- com.google.auto.value:auto-value-annotations:jar:1.10.2:compile
[INFO] +- com.google.api-client:google-api-client:jar:2.2.0:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.14:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.34.1:compile
[INFO] |  +- com.google.http-client:google-http-client-gson:jar:1.42.3:compile
[INFO] |  +- com.google.http-client:google-http-client-apache-v2:jar:1.42.3:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  \- com.google.http-client:google-http-client:jar:1.42.3:compile
[INFO] |     \- io.opencensus:opencensus-contrib-http-util:jar:0.31.1:compile
[INFO] +- com.google.http-client:google-http-client-jackson2:jar:1.43.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.2:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.12:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- com.pads:pads-analysis:jar:1.0.8:compile
[INFO] |  +- org.springframework:spring-core:jar:5.2.9.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.2.9.RELEASE:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  +- org.rosuda.REngine:Rserve:jar:1.8.1:compile
[INFO] |  |  \- org.rosuda.REngine:REngine:jar:2.1.0:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.10:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.16.0:compile
[INFO] \- org.apache.logging.log4j:log4j-to-slf4j:jar:2.16.0:compile

Note : in 26.0.0 with v14 everything works perfectly;

Any guidance or assistance in resolving this issue would be highly appreciated.
Thank you for your attention to this matter.

**Comment by jradcliff** [comment]
Is that the complete output from Maven `dependency:tree`? I'm not seeing any conflicting versions of `com.google.auth:google-auth-library-oauth2-http` or `com.google.auth:google-auth-library-credentials` (where `GdchCredentials` is defined).

You could try specifying the JVM arg of `-verbose:class` so you can see the source of each class as your application runs. That should highlight if classes from the `com.google.auth.oauth2` package are being loaded from an unexpected version.

**Comment by jradcliff** [comment]
Please reopen this issue if you're still encountering problems.
